#-------------------------------------------------------------
# JDBC ???? (DataSourceConfigurationProperties ?????)
#-------------------------------------------------------------
dbcp2.jdbc:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/petdb?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST&connectionTimeZone=SERVER
  username: root
  password: password
  initial-size: 1
  max-idle: 3
  min-idle: 1

#-------------------------------------------------------------
# MyBatis ??
#-------------------------------------------------------------
mybatis:
  mapper-locations: classpath:com/assqr/gido/repository/mybatis/*.yml

#-------------------------------------------------------------
# ???? (SQL ????????????????)
#-------------------------------------------------------------
logging.level:
  com.assqr.gido.repository: debug
  org.springframework.jdbc.datasource.DataSourceTransactionManager: debug

#-------------------------------------------------------------
# ?????????????????????????
#-------------------------------------------------------------
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petdb?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=JST&connectionTimeZone=SERVER
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
